---
# chocomilk vars

# Package Changelog
changelog: "https://release-monitoring.org/api/v2/versions/?project_id=378130"
changelog_format: json

# Regex for Version
version: "{{ register_changelog.json['latest_version'] }}"

# Download URL
url: "https://downloads.lexmark.com/downloads/drivers/Lexmark_Universal_v2_UD1_Installation_Package_{{ version }}.exe"

searchreplace:
  "tools/chocolateyinstall.ps1":
    - regwxp: (^\s*[$]*url\s*=\s*)('.*')
      replace: "$url = '{{ url }}'"
    - regwxp: (^\s*[$]*checksum\s*=\s*)('.*')
      replace: "$checksum = '{{ file_hash }}'"

# readme to description
readme:
  start: 4
  end: 20

# deploy
deploy:
  - provider: chocolatey
    repository: "https://push.chocolatey.org/"
    key: "{{ lookup('env','CHOCOLATEY_ORG_API_KEY') }}"
  - provider: github
    name: "OpenCircle-Choco-Bot"
    email: "chocomilk@open-circle.ch"
    url: github.com/open-circle-ltd/chocolatey.wwphone.git
    key: "{{ lookup('env','GITHUB_API_KEY') }}"

# Notification
notifications:
  - provider: mattermost
    url: 'https://chat.open-circle.ch'
    key: "{{ lookup('env','MATTERMOST_API_KEY') }}"
    channel: 'notification-chocolatey'
